[build]
  command = "npm install && npm run build"
  publish = "."  

[build.environment]
  NODE_VERSION = "18.16.1"  

[build.lifecycle]
  onPreBuild = "echo 'Running pre-build commands'"
  onBuild = "echo 'Running build commands'"
  onPostBuild = "echo 'Running post-build commands'"
